### ISSUE TITLE
你不是已经写过一个sso了吗……

### ISSUE THREAD

**Issue by SmallOyster** [ddawx123/phpSSOExample#1]
RT，想了解一下有什么不同 :joy:

**Comment by ddawx123** [comment]
这个是别人写的模型，看着架构比我原先那个好，而且是基于PHP的。JSP的cas我已经线上投入使用了，但是总觉得JSP开销太大。。

**Comment by SmallOyster** [comment]
哦……刚好我最近也想要SSO，就是找不到比较简单的 :joy: 

其实CAS应该比较专业一点吧……就是我一直都不会搞JSP->PHP

谢谢你了。

**Comment by SmallOyster** [comment]
里面的Java部分就没毛用了 :joy:

**Comment by ddawx123** [comment]
没有啊 cas服务端安装好以后 现有的ASP/PHP应用程序接入很方便的

**Comment by SmallOyster** [comment]
就是不会搞啊[捂脸]，我连JSP环境都搭不好 :sob: 对接就更不用说我会写了……

**Comment by ddawx123** [comment]
里面还有个csrf攻击模拟，他的project太乱了😂 下次pull下来整理一下。我是segmentfault里看到的文章，感觉很好就赶紧转存github了

**Comment by SmallOyster** [comment]
哦……先下载看看先啦，谢谢哈

**Comment by SmallOyster** [comment]
你那个好像太高大上……看不懂

**Comment by ddawx123** [comment]
下次有空我发个教程就行，真的很简单的。winserver和linux皆可

**Comment by SmallOyster** [comment]
嗯嗯
